name: build

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # required for OIDC
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          load: true
          tags: actions-k8s-ci:candidate

      - name: Run image smoke tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            actions-k8s-ci:candidate \
            testdata/image/test.sh

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::245976212095:role/github-actions/geoffmore/actions-k8s-ci/ecr-push
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Push image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: true
          tags: |
            public.ecr.aws/e3l5p3n5/geoffmore/actions-k8s-ci:latest
            public.ecr.aws/e3l5p3n5/geoffmore/actions-k8s-ci:${{ github.sha }}
            public.ecr.aws/e3l5p3n5/geoffmore/actions-k8s-ci:r${{ github.run_number }}
