name: test-image

on:
  pull_request:
    paths:
      - Dockerfile
      - testdata/image/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t actions-k8s-ci:pr .

      - name: Run image smoke tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            actions-k8s-ci:pr \
            testdata/image/test.sh
