name: test-image

on:
  pull_request:
    paths:
      - Dockerfile
      - testdata/image/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run image smoke tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            public.ecr.aws/e3l5p3n5/geoffmore/actions-k8s-ci:latest \
            testdata/image/test.sh
